name: Build

on: [push, workflow_dispatch]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      CMC_API_KEY: ${{ secrets.CMC_API_KEY }}
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: temurin

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2
      
      - name: Create local.properties file
        run: echo "CMC_API_KEY=$CMC_API_KEY" > local.properties

      - name: Build SampleApplication
        run: ./gradlew assembleRelease

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: apk
          path: app/build/outputs/apk/
